# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_rst_ps8_0_100M_1/ultra96v2_bd_rst_ps8_0_100M_1.xci
# IP: The module: 'ultra96v2_bd_rst_ps8_0_100M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_rst_ps8_0_100M_1/ultra96v2_bd_rst_ps8_0_100M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra96v2_bd_rst_ps8_0_100M_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_rst_ps8_0_100M_1/ultra96v2_bd_rst_ps8_0_100M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra96v2_bd_rst_ps8_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_rst_ps8_0_100M_1/ultra96v2_bd_rst_ps8_0_100M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra96v2_bd_rst_ps8_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_rst_ps8_0_100M_1/ultra96v2_bd_rst_ps8_0_100M_1.xci
# IP: The module: 'ultra96v2_bd_rst_ps8_0_100M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_rst_ps8_0_100M_1/ultra96v2_bd_rst_ps8_0_100M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra96v2_bd_rst_ps8_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_rst_ps8_0_100M_1/ultra96v2_bd_rst_ps8_0_100M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra96v2_bd_rst_ps8_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_rst_ps8_0_100M_1/ultra96v2_bd_rst_ps8_0_100M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra96v2_bd_rst_ps8_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
