@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun May 17 18:56:48 +0100 2020
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim ultra96v2_bd_wrapper_behav -key {Behavioral:sim_1:Functional:ultra96v2_bd_wrapper} -tclbatch ultra96v2_bd_wrapper.tcl -protoinst "protoinst_files/ultra96v2_bd.protoinst" -view C:/xilinxdesigns/sdraproject/ultra96v2_0-master/ultra96v2_bd_wrapper_behav.wcfg -log simulate.log"
call xsim  ultra96v2_bd_wrapper_behav -key {Behavioral:sim_1:Functional:ultra96v2_bd_wrapper} -tclbatch ultra96v2_bd_wrapper.tcl -protoinst "protoinst_files/ultra96v2_bd.protoinst" -view C:/xilinxdesigns/sdraproject/ultra96v2_0-master/ultra96v2_bd_wrapper_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
