# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/xilinxdesigns/sdraproject/ultra96v2_0-master/ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_axis_dwidth_converter_1_0/ultra96v2_bd_axis_dwidth_converter_1_0.xci
# IP: The module: 'ultra96v2_bd_axis_dwidth_converter_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/xilinxdesigns/sdraproject/ultra96v2_0-master/ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_axis_dwidth_converter_1_0/ultra96v2_bd_axis_dwidth_converter_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra96v2_bd_axis_dwidth_converter_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/xilinxdesigns/sdraproject/ultra96v2_0-master/ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_axis_dwidth_converter_1_0/ultra96v2_bd_axis_dwidth_converter_1_0.xci
# IP: The module: 'ultra96v2_bd_axis_dwidth_converter_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/xilinxdesigns/sdraproject/ultra96v2_0-master/ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_axis_dwidth_converter_1_0/ultra96v2_bd_axis_dwidth_converter_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra96v2_bd_axis_dwidth_converter_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
