#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : ultra96v2_bd.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Sun May 17 18:52:24 +0100 2020
# SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved. 
#
# usage: ultra96v2_bd.sh [-help]
# usage: ultra96v2_bd.sh [-lib_map_path]
# usage: ultra96v2_bd.sh [-noclean_files]
# usage: ultra96v2_bd.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'ultra96v2_bd.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_6 zynq_ultra_ps_e_vip_v1_0_6 xil_defaultlib axi_lite_ipif_v3_0_4 lib_cdc_v1_0_2 interrupt_control_v3_1_4 axi_gpio_v2_0_22 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_20 fifo_generator_v13_2_5 axi_data_fifo_v2_1_19 axi_crossbar_v2_1_21 proc_sys_reset_v5_0_13 axi_bram_ctrl_v4_1_2 blk_mem_gen_v8_4_4 lib_pkg_v1_0_2 lib_srl_fifo_v1_0_2 axi_uart16550_v2_0_22 xlslice_v1_0_2 xlconcat_v2_1_3 axis_infrastructure_v1_1_0 axis_register_slice_v1_1_20 axis_dwidth_converter_v1_1_19 xbip_utils_v3_0_10 axi_utils_v2_0_6 fir_compiler_v7_2_13 axis_broadcaster_v1_1_19 cic_compiler_v4_0_15 axis_combiner_v1_1_18 xbip_pipe_v3_0_6 xbip_bram18k_v3_0_6 mult_gen_v12_0_16 cmpy_v6_0_18 xbip_dsp48_wrapper_v3_0_4 xbip_dsp48_addsub_v3_0_6 xbip_dsp48_multadd_v3_0_6 dds_compiler_v6_0_19 sim_clk_gen_v1_0_2 xlconstant_v1_1_6 axi_protocol_converter_v2_1_20 axi_clock_converter_v2_1_19 axi_dwidth_converter_v2_1_20)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "ultra96v2_bd.sh - Script generated by export_simulation (Vivado v2019.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "C:/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "C:/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "C:/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "C:/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "C:/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_6 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/dc12/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work zynq_ultra_ps_e_vip_v1_0_6 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim/ultra96v2_bd_zynq_ultra_ps_e_0_0_vip_wrapper.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_22 $vhdlan_opts \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/f71e/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_axi_gpio_0_0/sim/ultra96v2_bd_axi_gpio_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/72d4/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/60de/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/6b0d/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_xbar_0/sim/ultra96v2_bd_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_rst_ps8_0_100M_1/sim/ultra96v2_bd_rst_ps8_0_100M_1.vhd" \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_axi_gpio_0_1/sim/ultra96v2_bd_axi_gpio_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_bram_ctrl_v4_1_2 $vhdlan_opts \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/a002/hdl/axi_bram_ctrl_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_axi_bram_ctrl_0_0/sim/ultra96v2_bd_axi_bram_ctrl_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_blk_mem_gen_0_0/sim/ultra96v2_bd_blk_mem_gen_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_uart16550_v2_0_22 $vhdlan_opts \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/7d1b/hdl/axi_uart16550_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_axi_uart16550_0_0/sim/ultra96v2_bd_axi_uart16550_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlslice_v1_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/11d0/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_xlslice_0_0/sim/ultra96v2_bd_xlslice_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/442e/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_xlconcat_0_0/sim/ultra96v2_bd_xlconcat_0_0.v" \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_clk_wiz_0_0/ultra96v2_bd_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_clk_wiz_0_0/ultra96v2_bd_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_register_slice_v1_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/00d6/hdl/axis_register_slice_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_dwidth_converter_v1_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/f22d/hdl/axis_dwidth_converter_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_axis_dwidth_converter_0_0/sim/ultra96v2_bd_axis_dwidth_converter_0_0.v" \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_axis_dwidth_converter_1_0/sim/ultra96v2_bd_axis_dwidth_converter_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/b795/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_6 $vhdlan_opts \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/1971/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work fir_compiler_v7_2_13 $vhdlan_opts \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/352e/hdl/fir_compiler_v7_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_fir_compiler_0_0/sim/ultra96v2_bd_fir_compiler_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_axis_broadcaster_0_0/hdl/tdata_ultra96v2_bd_axis_broadcaster_0_0.v" \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_axis_broadcaster_0_0/hdl/tuser_ultra96v2_bd_axis_broadcaster_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_broadcaster_v1_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/d7e4/hdl/axis_broadcaster_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_axis_broadcaster_0_0/hdl/top_ultra96v2_bd_axis_broadcaster_0_0.v" \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_axis_broadcaster_0_0/sim/ultra96v2_bd_axis_broadcaster_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work cic_compiler_v4_0_15 $vhdlan_opts \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0aa2/hdl/cic_compiler_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_cic_compiler_0_0/sim/ultra96v2_bd_cic_compiler_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axis_combiner_v1_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ddc9/hdl/axis_combiner_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_axis_combiner_0_0/sim/ultra96v2_bd_axis_combiner_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/7468/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/d367/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_16 $vhdlan_opts \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ce84/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work cmpy_v6_0_18 $vhdlan_opts \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/231d/hdl/cmpy_v6_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_cmpy_0_0/sim/ultra96v2_bd_cmpy_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/910d/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_multadd_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/b0ac/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work dds_compiler_v6_0_19 $vhdlan_opts \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/c3fd/hdl/dds_compiler_v6_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_dds_compiler_0_0/sim/ultra96v2_bd_dds_compiler_0_0.vhd" \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_cic_compiler_0_1/sim/ultra96v2_bd_cic_compiler_0_1.vhd" \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_proc_sys_reset_0_0/sim/ultra96v2_bd_proc_sys_reset_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_bus_to_axis_0_0/sim/ultra96v2_bd_bus_to_axis_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_dds_compiler_1_0/sim/ultra96v2_bd_dds_compiler_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work sim_clk_gen_v1_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/b740/hdl/sim_clk_gen_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_sim_clk_gen_0_0/sim/ultra96v2_bd_sim_clk_gen_0_0.v" \
    "$ref_dir/../../../bd/ultra96v2_bd/sim/ultra96v2_bd.v" \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_xlslice_0_2/sim/ultra96v2_bd_xlslice_0_2.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/34f7/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_xlconstant_0_0/sim/ultra96v2_bd_xlconstant_0_0.v" \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_xlslice_3_0/sim/ultra96v2_bd_xlslice_3_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/c4a6/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/9e81/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/d394/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/4fba" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ultra96v2_0.srcs/sources_1/bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_auto_ds_0/sim/ultra96v2_bd_auto_ds_0.v" \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_auto_pc_0/sim/ultra96v2_bd_auto_pc_0.v" \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_auto_ds_1/sim/ultra96v2_bd_auto_ds_1.v" \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_auto_pc_1/sim/ultra96v2_bd_auto_pc_1.v" \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_auto_ds_2/sim/ultra96v2_bd_auto_ds_2.v" \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_auto_ds_3/sim/ultra96v2_bd_auto_ds_3.v" \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_auto_pc_2/sim/ultra96v2_bd_auto_pc_2.v" \
    "$ref_dir/../../../bd/ultra96v2_bd/ip/ultra96v2_bd_cvt_offset_binary_0_0/sim/ultra96v2_bd_cvt_offset_binary_0_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.ultra96v2_bd xil_defaultlib.glbl -o ultra96v2_bd_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./ultra96v2_bd_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./ultra96v2_bd.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key ultra96v2_bd_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc ultra96v2_bd_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./ultra96v2_bd.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: ultra96v2_bd.sh [-help]\n\
Usage: ultra96v2_bd.sh [-lib_map_path]\n\
Usage: ultra96v2_bd.sh [-reset_run]\n\
Usage: ultra96v2_bd.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
